version: 2

updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
      time: "11:00"
    labels:
      - actions
      - dependencies
      - auto-squash

  # Maintain dependencies for npm/yarn
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: weekly
      time: "11:00"
    open-pull-requests-limit: 10
    versioning-strategy: lockfile-only
    labels:
      - javascript
      - dependencies
      - auto-squash

  # Maintain dependencies for Composer
  - package-ecosystem: composer
    directory: "/"
    schedule:
      interval: weekly
      time: "11:00"
    open-pull-requests-limit: 10
    versioning-strategy: lockfile-only
    labels:
      - php
      - dependencies
      - auto-squash
