on: push
name: phpunit / phpinsights / php-cs-fixer
jobs:
  php-cs-fixer:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: php-cs-fixer
      uses: docker://oskarstark/php-cs-fixer-ga
    - name: composer install
      uses: MilesChou/composer-action@master
      with:
        args: install -q --no-ansi --no-interaction --no-scripts --no-suggest --no-progress
          --prefer-dist
    - name: phpinsights
      uses: stefanzweifel/laravel-phpinsights-action@v1.0.0
      with:
        args: -v --min-quality=80 --min-complexity=80 --min-architecture=80 --min-style=80
    - name: phpunit
      uses: ./actions/run-phpunit/
      with:
        args: tests/
